version: '2'

services:
  hugo:
    image: 'nginx:stable-alpine'
    depends_on:
      - 'hugo-builder'
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:80']
    labels:
      traefik.enable: true
      traefik.http.routers.hugo.rule: 'Host(`hugo.${SITE:-localhost}`)'
      traefik.http.services.hugo.loadbalancer.server.port: 80
    networks:
      - 'srv'
    restart: 'always'
    volumes:
      - './nginx/conf:/etc/nginx/conf.d'
      - './nginx/logs:/var/log/nginx/'

  hugo-builder:
    image: 'jojomi/hugo:0.59'
    environment:
      HUGO_BASEURL: 'https://hugo.${SITE:-localhost}/'
      HUGO_REFRESH_TIME: 3600
      HUGO_THEME: 'hugo-theme-cactus-plus'
    labels:
      traefik.enable: false
    restart: 'always'
    volumes:
      - './blog:/src'
      - './nginx/conf/www:/output'
