version: '2'

services:
  vpn:
    image: 'hwdsl2/ipsec-vpn-server:${VPN_IMAGE_VERSION:-latest}'
    environment:
      VPN_ADDL_PASSWORDS: '${VPN_ADDL_PASSWORDS:-}' # space separated values
      VPN_ADDL_USERS: '${VPN_ADDL_USERS:-}' # space separated values
      VPN_IPSEC_PSK: '${VPN_IPSEC_PSK:-}'
      VPN_PASSWORD: '${VPN_PASSWORD:-}'
      VPN_USER: '${VPN_USER:-}'
    privileged: true
    restart: 'always'
    ports:
      - '4500:4500/udp'
      - '500:500/udp'
    volumes:
      - '/lib/modules:/lib/modules:ro'
