version: '2'

services:
  sonarr:
    image: 'linuxserver/sonarr:${SONARR_IMAGE_VERSION:-4.0.0}'
    environment:
      PGID: '${SONARR_GPID:-1000}'
      PUID: '${SONARR_PUID:-1000}'
      TZ: '${TZ:-Europe/Paris}'
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.middlewares: 'basic_auth@docker'
      traefik.http.routers.sonarr.rule: 'Host(`sonarr.${SITE:-localhost}`)'
      traefik.http.services.sonarr.loadbalancer.server.port: 8080
    links:
      - 'jackett'
      - 'transmission'
    networks:
      - 'srv'
    restart: 'always'
    volumes:
      - './sonarr/config:/config'
      - './sonarr/downloads:/downloads'
      - './sonarr/tv:/tv'
