version: '2'

services:
  streama:
    image: gkiko/streama:v1.8.3
    volumes:
      - './transmission/downloads:/data'
      - './streama/streama.mv.db:/app/streama/streama.mv.db'
      - './streama/streama.trace.db:/app/streama/streama.trace.db'
    networks:
      - 'srv'
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:8080/login/auth']
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:streama.${SITE}'
      - 'traefik.port=8080'
