version: '2'

services:
  streama:
    image: 'gkiko/streama:v1.8.3'
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:8080/login/auth']
    labels:
      traefik.enable: true
      traefik.http.routers.streama.rule: 'Host(`streama.${SITE:-localhost}`)'
      traefik.http.services.streama.loadbalancer.server.port: 8080
    networks:
      - 'srv'
    restart: 'always'
    volumes:
      - './streama/streama.mv.db:/app/streama/streama.mv.db'
      - './streama/streama.trace.db:/app/streama/streama.trace.db'
      - './transmission/downloads:/data'
