version: '2'

services:
  bitwarden:
    image: 'vaultwarden/server:${BITWARDEN_IMAGE_VERSION:-latest}'
    environment:
      ADMIN_TOKEN: '${USERS}'
      # to enable U2F and FIDO2 WebAuthn authentication
      DOMAIN: 'https://bitwarden.${SITE:-localhost}'
      PASSWORD_ITERATIONS: 500000
      ROCKET_PORT: 8080
      # whether users are allowed to create Bitwarden Sends/
      SENDS_ALLOWED: 'true'
      SIGNUPS_ALLOWED: 'true'
      # if new users need to verify their email address upon registration
      SIGNUPS_VERIFY: 'false'
      TZ: '${TZ:-Europe/Paris}'
    labels:
      traefik.enable: true
      traefik.http.routers.bitwarden-admin.middlewares: 'basic_auth@docker'
      traefik.http.routers.bitwarden-admin.rule: |
        'Host(`bitwarden.${SITE:-localhost}`) && PathPrefix(`/admin`)'
      traefik.http.routers.bitwarden-user.rule: |
        'Host(`bitwarden.${SITE:-localhost}`) && !PathPrefix(`/admin`)'
      traefik.http.services.bitwarden.loadbalancer.server.port: 8080
    networks:
      - 'srv'
    restart: 'always'
    user: 'nobody'
    volumes:
      - './bitwarden/data:/data'
