version: '2'

services:
  bitwarden:
    image: vaultwarden/server:latest
    user: nobody
    environment:
      - ROCKET_PORT=8080
      - ADMIN_TOKEN=${USERS}
    volumes:
      - ./bitwarden/data:/data
    networks:
      - 'srv'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bitwarden-user.rule=Host(`bitwarden.${SITE:-localhost}`) && !PathPrefix(`/admin`)'
      - 'traefik.http.routers.bitwarden-admin.rule=Host(`bitwarden.${SITE:-localhost}`) && PathPrefix(`/admin`)'
      - 'traefik.http.routers.bitwarden-admin.middlewares=basic_auth@docker'
      - 'traefik.http.services.bitwarden.loadbalancer.server.port=8080'
