version: '2'

networks:
  hits-internal: {}

services:
  hits:
    image: 'tommoulard/hits'
    depends_on:
      - 'hits-postgresql'
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:4000']
    labels:
      traefik.enable: true
      traefik.http.routers.hits.rule: 'Host(`hits.${SITE:-localhost}`)'
      traefik.http.services.hits.loadbalancer.server.port: 4000
    networks:
      - 'hits-internal'
      - 'srv'
    restart: 'always'

  hits-postgresql:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    networks:
      hits-internal:
        aliases:
          - 'postgresql'
    restart: 'always'
    user: '1000:1000'
    volumes:
      - './postgresql/:/var/lib/postgresql/data'
