version: '2'

services:
  theia:
    image: 'theiaide/theia'
    init: true
    labels:
      traefik.enable: true
      traefik.http.routers.theia.middlewares: 'basic_auth@docker'
      traefik.http.routers.theia.rule: 'Host(`theia.${SITE:-localhost}`)'
      traefik.http.services.theia.loadbalancer.server.port: 3000
    networks:
      - 'srv'
    restart: 'always'
    # With this, you cannot install plugins but you can save files
    user: '1000:1000'
    volumes:
      - '${HOME}:/home/project:cached'
