version: '2'

networks:
  framadate-internal: {}

services:
  framadate:
    image: 'xgaia/framadate:${FRAMADATE_IMAGE_VERSION:-latest}'
    depends_on:
      - 'framadate-db'
    environment:
      ADMIN_PASSWORD: '${FRAMADATE_ADMIN_PASSWORD:-pass}'
      APP_NAME: 'Framadate'
      APP_URL: 'framadate.${SITE:-localhost}'
      DEFAULT_POLL_DURATION: '365'
      MARKDOWN_EDITOR_BY_DEFAULT: 'true'
      MYSQL_DATABASE: '${FRAMADATE_MYSQL_DATABASE:-framadate}'
      MYSQL_PASSWORD: '${FRAMADATE_MYSQL_PASSWORD:-framadate}'
      MYSQL_ROOT_PASSWORD: '${FRAMADATE_MYSQL_ROOT_PASSWORD:-pass}'
      MYSQL_USER: '${FRAMADATE_MYSQL_USER:-framadate}'
      PROVIDE_FORK_AWESOME: 'true'
      SERVERNAME: 'framadate.${SITE:-localhost}'
      SHOW_CULTIVATE_YOUR_GARDEN: 'true'
      SHOW_THE_SOFTWARE: 'true'
      SHOW_WHAT_IS_THAT: 'true'
      USER_CAN_ADD_IMG_OR_LINK: 'true'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.framadate.rule=Host(`framadate.${SITE:-localhost}`)'
      - 'traefik.http.services.framadate.loadbalancer.server.port=80'
    restart: 'always'
    networks:
      - 'framadate-internal'
      - 'srv'

  framadate-db:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: '${FRAMADATE_MYSQL_DATABASE:-framadate}'
      MYSQL_PASSWORD: '${FRAMADATE_MYSQL_PASSWORD:-framadate}'
      MYSQL_ROOT_PASSWORD: '${FRAMADATE_MYSQL_ROOT_PASSWORD:-pass}'
      MYSQL_USER: '${FRAMADATE_MYSQL_USER:-framadate}'
    healthcheck:
      test: ['CMD', 'mysqlcheck', '--all-databases', '-ppass']
    labels:
      - 'traefik.enable=false'
    networks:
      - 'framadate-internal'
    restart: 'always'
    volumes:
      - './db:/var/lib/mysql'
