version: '2'

services:
  musicbot:
    image: 'raiponce/musicbot:0.2.10'
    labels:
      traefik.enable: false
    networks:
      - 'srv'
    restart: 'always'
    volumes:
      - './musicbot/conf:/musicBot/conf/'
      - './musicbot/playlists:/musicBot/playlists/'
