version: '2'

# See https://blog.jessfraz.com/post/running-a-tor-relay-with-docker/
# Checkout logs and https://atlas.torproject.org/ for annalytics

services:
  tor-relay:
    image: 'jess/tor-relay'
    build: 'https://github.com/jessfraz/dockerfiles.git#:tor-relay'
    environment:
      # see https://github.com/jessfraz/dockerfiles/tree/master/tor-relay for
      # further information about the values
      CONTACT_EMAIL: '${ROOT_EMAIL:-changeme@changeme.org}'
      CONTACT_GPG_FINGERPRINT: '${TOR_CONTACT_GPG_FINGERPRINT:-}'
      CONTACT_NAME: '${USERNAME}'
      RELAY_BANDWIDTH_BURST: '${TOR_RELAY_BANDWIDTH_BURST:-200 KBytes}'
      RELAY_BANDWIDTH_RATE: '${TOR_RELAY_BANDWIDTH_RATE:-100 KBytes}'
      RELAY_NICKNAME: '${TOR_RELAY_NICKNAME:-hacktheplanet}'
      RELAY_PORT: 9001
      RELAY_TYPE: '${TOR_RELAY_TYPE:-middle}' # bridge, middle, or exit
    labels:
      traefik.enable: false
    networks:
      - 'srv'
    ports:
      - '9001:9001'
    restart: 'always'
    volumes:
      - './keys:/var/lib/tor/.tor/keys/'
      - '/etc/localtime:/etc/localtime'
