version: '2'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:${GITLAB_IMAGE_VERSION:-latest}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.${SITE:-localhost}:80'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    hostname: 'gitlab.${SITE:-localhost}'
    labels:
      traefik.enable: true
      traefik.http.routers.gitlab.rule: 'Host(`gitlab.${SITE:-localhost}`)'
      traefik.http.services.gitlab.loadbalancer.server.port: 80
    networks:
      - 'srv'
    ports:
      - '2224:22'
    restart: 'always'
    volumes:
      - './config:/etc/gitlab'
      - './data:/var/opt/gitlab'
      - './logs:/var/log/gitlab'

  runner:
    image: 'gitlab/gitlab-runner:${GITLAB_RUNNER_IMAGE_VERSION:-latest}'
    labels:
      traefik.enable: false
    links:
      - 'gitlab'
    restart: 'always'
    volumes:
      - './runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
