version: '2'

services:
  jackett:
    image: linuxserver/jackett:v0.15.5-ls61
    environment:
      - PUID=1000
      - PGID=1000
      - 'TZ=${TZ}'
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    networks:
      - 'srv'
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:9117/UI/Login?ReturnUrl=%2FUI%2FDashboard']
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:jackett.${SITE}'
      - 'traefik.port=9117'
      - 'traefik.frontend.auth.basic.users=${USERS}'
      # - 'traefik.frontend.auth.forward.address=http://authelia:9091/api/verify?rd=https://authelia.${SITE}/'
      # - 'traefik.frontend.auth.forward.trustForwardHeader=true'
      # - 'traefik.frontend.auth.forward.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
