version: '2'

networks:
  rocketchat-internal:

services:
  rocketchat-mongo:
    image: mongo:4.0
    command: mongod --smallfiles --oplogSize 128 --replSet rs01
    volumes:
      - './rocketchat/db/:/data/db'
    networks:
      - 'rocketchat-internal'
    labels:
      - 'traefik.enable=false'

  rocketchat-mongo-replica:
    image: mongo:4.0
    command: 'mongo rocketchat-mongo/rocketchat --eval "rs.initiate({ _id: ''rs01'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    networks:
      - 'rocketchat-internal'
    depends_on:
      - 'rocketchat-mongo'
    labels:
      - 'traefik.enable=false'

  rocketchat:
    image: rocket.chat:latest
    restart: unless-stopped
    environment:
      - 'ROOT_URL=https://rocketchat.${SITE}'
      - 'MONGO_URL=mongodb://rocketchat-mongo:27017/rocketchat'
      - 'MONGO_OPLOG_URL=mongodb://rocketchat-mongo:27017/local'
    networks:
      - 'srv'
      - 'rocketchat-internal'
    depends_on:
      - 'rocketchat-mongo'
      - 'rocketchat-mongo-replica' # replica is mandatory
    volumes:
      - './rocketchat/uploads:/app/uploads'
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:rocketchat.${SITE}'
      - 'traefik.port=3000'

  # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
  rocketchat-hubot:
    image: rocketchat/hubot-rocketchat:latest
    restart: unless-stopped
    environment:
      - 'ROCKETCHAT_URL=rocketchat:3000'
      - 'ROCKETCHAT_ROOM=GENERAL'
      - 'ROCKETCHAT_USER=bot'
      - 'ROCKETCHAT_PASSWORD=botpassword'
      - 'BOT_NAME=bot'
      # you can add more scripts as you'd like here, they need to be installable by npm
      # - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    depends_on:
      - 'rocketchat'
    volumes:
      - './rocketchat/scripts:/home/hubot/scripts'
    # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
    # ports:
      # - 3001:8080
    labels:
      - 'traefik.enable=false'
