version: '2'

services:
  jellyfin:
    image: jellyfin/jellyfin
    volumes:
      - './jellyfin/config:/config'
      - './jellyfin/cache:/cache'
      - './jellyfin/media:/media'
      - './jellyfin/logs:/logs'
    networks:
      - 'srv'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.${SITE:-localhost}`)'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'
