version: '2'

services:
  jellyfin:
    image: 'jellyfin/jellyfin'
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.rule: 'Host(`jellyfin.${SITE:-localhost}`)'
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
    networks:
      - 'srv'
    restart: 'always'
    user: '1000:1000'
    volumes:
      - './jellyfin/cache:/cache'
      - './jellyfin/config:/config'
      - './jellyfin/logs:/logs'
      - './jellyfin/media:/media'
