version: '2'

services:
  peertube:
    image: 'chocobozzz/peertube:production-buster'
    depends_on:
      - 'peertube-db'
      - 'peertube-redis'
    environment:
      PEERTUBE_ADMIN_EMAIL: '${ROOT_EMAIL:-changeme@changeme.org}'
      PEERTUBE_DB_HOSTNAME: 'peertube-db'
      PEERTUBE_DB_PASSWORD: '${USERS}'
      PEERTUBE_DB_USERNAME: 'peertube'
      PEERTUBE_TRUST_PROXY: '["127.0.0.1", "loopback", "172.0.0.0/0"]'
      PEERTUBE_WEBSERVER_HOSTNAME: 'peertube.${SITE:-localhost}'
      PEERTUBE_WEBSERVER_HTTPS: true
      PEERTUBE_WEBSERVER_PORT: 443
    labels:
      traefik.enable: true
      traefik.http.routers.peertube.rule: 'Host(`peertube.${SITE:-localhost}`)'
      traefik.http.services.peertube.loadbalancer.server.port: 9000
    links:
      - 'peertube-db'
      - 'peertube-redis'
    networks:
      - 'srv'
    restart: 'always'
    volumes:
      - './peertube/config:/config'
      - './peertube/data:/data'

  peertube-db:
    image: 'postgres:10-alpine'
    environment:
      POSTGRES_DB: 'peertube'
      POSTGRES_PASSWORD: '${USERS}'
      POSTGRES_USER: 'peertube'
    healthcheck:
      test: 'CMD pg_isready -U peertube'
    labels:
      traefik.enable: false
    networks:
      - 'srv'
    restart: 'always'
    volumes:
      - './peertube/db:/var/lib/postgresql/data'

  peertube-redis:
    image: 'redis:4-alpine'
    healthcheck:
      test: 'CMD redis-cli PING'
    labels:
      traefik.enable: false
    networks:
      - 'srv'
    restart: 'always'
    volumes:
      - './peertube/redis:/data'
