version: '2'

services:
  bazarr:
    image: 'linuxserver/bazarr:${BAZARR_IMAGE_VERSION:-v1.2.2}'
    environment:
      PGID: '${BAZARR_GPID:-1000}'
      PUID: '${BAZARR_PUID:-1000}'
      TZ: '${TZ:-Europe/Paris}'
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.middlewares: 'basic_auth@docker'
      traefik.http.routers.bazarr.rule: 'Host(`bazarr.${SITE:-localhost}`)'
      traefik.http.services.bazarr.loadbalancer.server.port: 8080
    links:
      - 'transmission'
      - 'jackett'
      - 'sonarr'
    networks:
      - 'srv'
    restart: 'always'
    volumes:
      - './config:/config'
      - './movies:/movies'
      - './tv:/tv'
