version: '2'

services:
  bazarr:
    image: linuxserver/bazarr:v0.8.3.4-ls61
    environment:
      - PUID=1000
      - PGID=1000
      - 'TZ=${TZ}'
    volumes:
      - ./bazarr/config:/config
      - ./bazarr/movies:/movies
      - ./bazarr/tv:/tv
    links:
      - transmission
      - jackett
      - sonarr
    networks:
      - 'srv'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:bazarr.${SITE}'
      - 'traefik.port=8080'
      - 'traefik.frontend.auth.basic.users=${USERS}'
      # - 'traefik.frontend.auth.forward.address=http://authelia:9091/api/verify?rd=https://authelia.${SITE}/'
      # - 'traefik.frontend.auth.forward.trustForwardHeader=true'
      # - 'traefik.frontend.auth.forward.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
