alerting:
  alertmanagers:
    - api_version: 'v1'
      scheme: 'http'
      static_configs:
        - targets:
            - 'alertmanager:9093'
      timeout: '10s'
global:
  evaluation_interval: '15s'
  scrape_interval: '15s'
  scrape_timeout: '10s'
rule_files:
  - '/etc/prometheus/rules/*.yaml'
scrape_configs:
  - honor_timestamps: true
    job_name: 'prometheus'
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: '15s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'localhost:9090'
  - honor_timestamps: true
    job_name: 'grafana'
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: '15s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'grafana:3000'
  - honor_timestamps: true
    job_name: 'node_exporter'
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: '15s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'node_exporter:9100'
  - honor_timestamps: true
    job_name: 'traefik'
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: '15s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'traefik:8080'
  - honor_timestamps: true
    job_name: 'cadvisor'
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: '15s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'cadvisor:8080'
  - honor_timestamps: true
    job_name: 'alertmanager'
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: '15s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'alertmanager:9093'
  - honor_timestamps: true
    job_name: 'hass' # home assistant
    metrics_path: '/api/prometheus'
    scheme: 'http'
    scrape_interval: '60s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'homeassistant:8123'
