version: '2'

services:
  minecraft:
    image: 'itzg/minecraft-server'
    environment:
      EULA: true
    restart: 'always'
    labels:
      - 'traefik.enable=false'
    ports:
      - '25565:25565/udp'
    volumes:
      - './minecraft/minecraft-data:/data'
