version: '2'

services:
  minecraft:
    image: jonasbonno/ftb-revelation
    ports:
      - '25565:25565/udp'
    volumes:
      - './minecraft/ftb-data:/minecraft'
    restart: always
    labels:
      - 'traefik.enable=false'
    environment:
      - EULA=TRUE
