version: '2'

services:
  transmission:
    image: linuxserver/transmission:2.94-r1-ls12
    environment:
      - 'PGID=1000'
      - 'PUID=1000'
      - 'TZ=${TZ}'
    ports:
      - '51413:51413'
      - '51413:51413/udp'
    volumes:
      - './transmission/config:/config'
      - './transmission/downloads:/downloads'
      - './transmission/watch:/watch'
    networks:
      - 'srv'
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:9091/transmission/web/']
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:transmission.${SITE}'
      - 'traefik.port=9091'
      - 'traefik.frontend.auth.basic.users=${USERS}'
      # - 'traefik.frontend.auth.forward.address=http://authelia:9091/api/verify?rd=https://authelia.${SITE}/'
      # - 'traefik.frontend.auth.forward.trustForwardHeader=true'
      # - 'traefik.frontend.auth.forward.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
