name: Tests

on:
  push:

jobs:
  Config-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: ./test.sh
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-artifacts
          path: |
            log.log
            *.patch
  Health-checks-nginx:
    runs-on: ubuntu-latest
    env:
      SERVICE: nginx
    steps:
      - uses: actions/checkout@v2
      - name: Caching
        uses: actions/cache@v2
        with:
          path: /var/lib/docker/
          key: ${{ runner.os }}-health-${{ github.job }}
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml up -d
      - name: Waiting for service startup (10s)
        run: sleep 10s
      - name: Check running containers
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps
      - name: Check health
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps | grep "Up (healthy)"
  Health-checks-blog:
    runs-on: ubuntu-latest
    env:
      SERVICE: blog
    steps:
      - uses: actions/checkout@v2
      - name: Caching
        uses: actions/cache@v2
        with:
          path: /var/lib/docker/
          key: ${{ runner.os }}-health-${{ github.job }}
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml up -d
      - name: Waiting for service startup (10s)
        run: sleep 10s
      - name: Check running containers
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps
      - name: Check health
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps | grep "Up (healthy)"
  Health-checks-peertube:
    runs-on: ubuntu-latest
    env:
      SERVICE: peertube
    steps:
      - uses: actions/checkout@v2
      - name: Caching
        uses: actions/cache@v2
        with:
          path: /var/lib/docker/
          key: ${{ runner.os }}-health-${{ github.job }}
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml up -d
      - name: Waiting for service startup (10s)
        run: sleep 10s
      - name: Check running containers
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps
      - name: Check health
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps | grep "Up (healthy)"
  Health-checks-transmission:
    runs-on: ubuntu-latest
    env:
      SERVICE: transmission
    steps:
      - uses: actions/checkout@v2
      - name: Caching
        uses: actions/cache@v2
        with:
          path: /var/lib/docker/
          key: ${{ runner.os }}-health-${{ github.job }}
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml up -d
      - name: Waiting for service startup (10s)
        run: sleep 10s
      - name: Check running containers
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps
      - name: Check health
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps | grep "Up (healthy)"
  Health-checks-nextcloud:
    runs-on: ubuntu-latest
    env:
      SERVICE: nextcloud
    steps:
      - uses: actions/checkout@v2
      - name: Caching
        uses: actions/cache@v2
        with:
          path: /var/lib/docker/
          key: ${{ runner.os }}-health-${{ github.job }}
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml up -d
      - name: Waiting for service startup (10s)
        run: sleep 10s
      - name: Check running containers
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps
      - name: Check health
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps | grep "Up (healthy)"
  Health-checks-jackett:
    runs-on: ubuntu-latest
    env:
      SERVICE: jackett
    steps:
      - uses: actions/checkout@v2
      - name: Caching
        uses: actions/cache@v2
        with:
          path: /var/lib/docker/
          key: ${{ runner.os }}-health-${{ github.job }}
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml up -d
      - name: Waiting for service startup (10s)
        run: sleep 10s
      - name: Check running containers
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps
      - name: Check health
        run: docker-compose -f docker-compose.yml -f ${SERVICE}/docker-compose.${SERVICE}.yml ps | grep "Up (healthy)"
