name: 'Tests'

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - '*'
  push: {}

jobs:
  Config-test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Run tests'
        run: './test.sh'
      - uses: 'actions/upload-artifact@v2'
        if: 'failure()'
        with:
          name: 'test-artifacts'
          path: |
            log.log
            *.patch
  Health-checks-traefik:
    uses: 'tomMoulard/make-my-server/.github/workflows/healthcheck.workflow.tmpl.yml@feat/yamllint'
    with:
      service_name: 'traefik'
  Health-checks-nginx:
    uses: 'tomMoulard/make-my-server/.github/workflows/healthcheck.workflow.tmpl.yml@feat/yamllint'
    with:
      service_name: 'nginx'
  Health-checks-hugo:
    uses: 'tomMoulard/make-my-server/.github/workflows/healthcheck.workflow.tmpl.yml@feat/yamllint'
    with:
      service_name: 'hugo'
  Health-checks-peertube:
    uses: 'tomMoulard/make-my-server/.github/workflows/healthcheck.workflow.tmpl.yml@feat/yamllint'
    with:
      service_name: 'peertube'
  Health-checks-transmission:
    uses: 'tomMoulard/make-my-server/.github/workflows/healthcheck.workflow.tmpl.yml@feat/yamllint'
    with:
      service_name: 'transmission'
  Health-checks-nextcloud:
    uses: 'tomMoulard/make-my-server/.github/workflows/healthcheck.workflow.tmpl.yml@feat/yamllint'
    with:
      service_name: 'nextcloud'
  Health-checks-jackett:
    uses: 'tomMoulard/make-my-server/.github/workflows/healthcheck.workflow.tmpl.yml@feat/yamllint'
    with:
      service_name: 'jackett'
  Health-checks-codimd:
    uses: 'tomMoulard/make-my-server/.github/workflows/healthcheck.workflow.tmpl.yml@feat/yamllint'
    with:
      service_name: 'codimd'
  Lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Install yamllint'
        run: 'pip install yamllint'
      - name: 'yamllint version'
        run: 'yamllint --version'
      - name: 'Lint YAML files'
        run: 'yamllint --format github .'
